version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: disabled
