name: 🐞 Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe the bug in as much detail as you can.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducible Test
      description: Please write a test that can reliably reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
