name: Build

on:
  push:
    paths-ignore:
      - '**.md'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization
        uses: ./.github/actions/init
        with:
          thunderstore-client: false

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
