name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necessary to retrieve the latest tag name
          fetch-depth: 0

      - name: Initialization
        uses: ./.github/actions/init
        with:
          thunderstore-client: true

      - name: Build
        run: dotnet build
        env:
          BuildThunderstorePackage: true

      - name: Publish
        run: tcli publish --config-path thunderstore.toml --file build/*.zip
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_AUTH_TOKEN }}

